# Modified from Lab 8 https://github.com/UncleSamTech/Lab8/blob/master/.github/workflows/android.yml
name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x ./gradlew
      - run: ./gradlew tasks
      - run: ./gradlew clean check
      - run: ./gradlew assemble
